#
# Makefile
# gbersac, 2015-06-29 21:42
#
# gl_gen_buffer.c cppfunction.c generate_mesh.c load_mesh.c
all:
	$(CXX)  -x c++ ../common/*.cpp *.cpp  -x c -o prog -I ../../../src/libft/inc -I ../../../src/libmath/inc -I ../../../src/scop/inc -I ~/.brew/include/ -I ~/project/mesh_renderer-42/src/glew/inc -I ~/project/mesh_renderer-42/src/glfw/inc -I ../ -L ~/project/mesh_renderer-42/src/glfw -lglfw3 -framework Cocoa -framework IOKit -framework CoreVideo -L ~/project/mesh_renderer-42/src/glew -lglew -framework OpenGL -L. -l AntTweakBar 
